source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SimpleColorPicker_Example', :exclusive => true do
  pod "SimpleColorPicker", :path => "../"
end

target 'SimpleColorPicker_Tests', :exclusive => true do
  pod "SimpleColorPicker", :path => "../"

  
end
